n = int(input('Digite um numero:'))
r = n ** (1/2)
print('O dobro de {} vale {}'.format(n, (n*2)))
print('O triplo de {} vale {}.'.format(n, (n*3),))
print('A raiz quadrada de {} é igual a {:.2f}.'.format(n, r))